mand_all <- scan("mandarin/sorted.uniq.txt", what="", sep="\n")
mand_hds <- scan("mandarin/head.txt",        what="", sep="\n")
mand_svs <- scan("mandarin/semi_vowel.txt",  what="", sep="\n")
mand_ncs <- scan("mandarin/nucleus.txt",     what="", sep="\n")
mand_lts <- scan("mandarin/last.txt",        what="", sep="\n")
mand_tns <- scan("mandarin/tone.txt",        what="", sep="\n")

cant_all <- scan("cantonese/sorted.uniq.txt", what="", sep="\n")
cant_hds <- scan("cantonese/head.txt",        what="", sep="\n")
cant_svs <- scan("cantonese/semi_vowel.txt",  what="", sep="\n")
cant_ncs <- scan("cantonese/nucleus.txt",     what="", sep="\n")
cant_lts <- scan("cantonese/last.txt",        what="", sep="\n")
cant_tns <- scan("cantonese/tone.txt",        what="", sep="\n")

kore_all <- scan("korean/sorted.uniq.txt", what="", sep="\n")
kore_hds <- scan("korean/head.txt",        what="", sep="\n")
kore_svs <- scan("korean/semi_vowel.txt",  what="", sep="\n")
kore_ncs <- scan("korean/nucleus.txt",     what="", sep="\n")
kore_lts <- scan("korean/last.txt",        what="", sep="\n")
kore_tns <- scan("korean/tone.txt",        what="", sep="\n")

viet_all <- scan("vietnamese/sorted.uniq.txt", what="", sep="\n")
viet_hds <- scan("vietnamese/head.txt",        what="", sep="\n")
viet_svs <- scan("vietnamese/semi_vowel.txt",  what="", sep="\n")
viet_ncs <- scan("vietnamese/nucleus.txt",     what="", sep="\n")
viet_lts <- scan("vietnamese/last.txt",        what="", sep="\n")
viet_tns <- scan("vietnamese/tone.txt",        what="", sep="\n")

japa_all <- scan("japanese/sorted.uniq.txt", what="", sep="\n")
japa_hds <- scan("japanese/head.txt",        what="", sep="\n")
japa_svs <- scan("japanese/semi_vowel.txt",  what="", sep="\n")
japa_ncs <- scan("japanese/nucleus.txt",     what="", sep="\n")
japa_lts <- scan("japanese/last.txt",        what="", sep="\n")
japa_tns <- scan("japanese/tone.txt",        what="", sep="\n")

