hanz_all <- scan("mandarin/sorted.uniq.txt", what="", sep="\n")
hanz_hds <- scan("mandarin/head.txt",        what="", sep="\n")
hanz_svs <- scan("mandarin/semi_vowel.txt",  what="", sep="\n")
hanz_ncs <- scan("mandarin/nucleus.txt",     what="", sep="\n")
hanz_lts <- scan("mandarin/last.txt",        what="", sep="\n")
hanz_tns <- scan("mandarin/tone.txt",        what="", sep="\n")

honz_all <- scan("cantonese/sorted.uniq.txt", what="", sep="\n")
honz_hds <- scan("cantonese/head.txt",        what="", sep="\n")
honz_svs <- scan("cantonese/semi_vowel.txt",  what="", sep="\n")
honz_ncs <- scan("cantonese/nucleus.txt",     what="", sep="\n")
honz_lts <- scan("cantonese/last.txt",        what="", sep="\n")
honz_tns <- scan("cantonese/tone.txt",        what="", sep="\n")

hanj_all <- scan("korean/sorted.uniq.txt", what="", sep="\n")
hanj_hds <- scan("korean/head.txt",        what="", sep="\n")
hanj_svs <- scan("korean/semi_vowel.txt",  what="", sep="\n")
hanj_ncs <- scan("korean/nucleus.txt",     what="", sep="\n")
hanj_lts <- scan("korean/last.txt",        what="", sep="\n")
hanj_tns <- scan("korean/tone.txt",        what="", sep="\n")

hont_all <- scan("vietnamese/sorted.uniq.txt", what="", sep="\n")
hont_hds <- scan("vietnamese/head.txt",        what="", sep="\n")
hont_svs <- scan("vietnamese/semi_vowel.txt",  what="", sep="\n")
hont_ncs <- scan("vietnamese/nucleus.txt",     what="", sep="\n")
hont_lts <- scan("vietnamese/last.txt",        what="", sep="\n")
hont_tns <- scan("vietnamese/tone.txt",        what="", sep="\n")

kanj_all <- scan("japanese/sorted.uniq.txt", what="", sep="\n")
kanj_hds <- scan("japanese/head.txt",        what="", sep="\n")
kanj_svs <- scan("japanese/semi_vowel.txt",  what="", sep="\n")
kanj_ncs <- scan("japanese/nucleus.txt",     what="", sep="\n")
kanj_lts <- scan("japanese/last.txt",        what="", sep="\n")
kanj_tns <- scan("japanese/tone.txt",        what="", sep="\n")

